#!/usr/bin/env bash

set -euxo pipefail

rm -rf build

CMAKE_OPTIONS=(
  -DLLVM_PARALLEL_{COMPILE,LINK,TABLEGEN}_JOBS=16
  -DLLVM_ENABLE_PROJECTS='clang;lld'
  -DCMAKE_BUILD_TYPE=MinSizeRel
  -DLLVM_BUILD_TOOLS=OFF
  -DLLVM_BUILD_UTILS=OFF
  -DCLANG_ENABLE_STATIC_ANALYZER=OFF
  -DCLANG_ENABLE_OBJC_REWRITER=OFF
  -DLLVM_TARGETS_TO_BUILD="WebAssembly"
  -DCLANG_VENDOR="WASIX"
  -DLLD_VENDOR="WASIX"
  -DLLVM_APPEND_VC_REV="OFF"
  -DLLVM_ENABLE_ZLIB="FORCE_ON"
  -DLLVM_ENABLE_ZSTD="FORCE_ON"
  -DLLVM_ENABLE_LIBXML2="OFF"
  -DLLVM_ENABLE_LIBEDIT="OFF"
  -DLLVM_ENABLE_BACKTRACES="OFF"
  -DLLVM_INCLUDE_BENCHMARKS="OFF"
  -DLLVM_INCLUDE_EXAMPLES="OFF"
  -DLLVM_INCLUDE_TESTS="OFF"
)

if test "$1" = "static"; then
  CMAKE_OPTIONS+=(
    -DBUILD_SHARED_LIBS="OFF"
    -DLLVM_BUILD_LLVM_DYLIB="OFF"
    -DLLVM_ENABLE_PIC="OFF"
    -DLLVM_STATIC_LINK_CXX_STDLIB="ON"
    -DLLVM_BUILD_STATIC="ON"
  )
fi

cmake llvm \
  -B build \
  -G Ninja \
  "${CMAKE_OPTIONS[@]}"