set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR wasm32)

set(CMAKE_SYSROOT $ENV{WASIX_SYSROOT}/../sysroot32-eh)
set(triple wasm32-wasi)

set(CMAKE_C_COMPILER wasixcc)
set(CMAKE_CXX_COMPILER wasix++)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER_TARGET ${triple})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

SET(CMAKE_C_FLAGS 
   "-sWASM_EXCEPTIONS=yes -sPIC=no -sSYSROOT=${CMAKE_SYSROOT} "
   CACHE STRING "" FORCE)

SET(CMAKE_CXX_FLAGS
   "-sWASM_EXCEPTIONS=yes -sPIC=no  -sSYSROOT=${CMAKE_SYSROOT} "
   CACHE STRING "" FORCE)